name: resolve_font_height
description: Flutter package to get the default font's height based on the current build context.

version: 1.0.0

homepage: https://github.com/zippa-pizza/resolve_font_height
repository: https://github.com/zippa-pizza/resolve_font_height

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
